#
# APP SETTINGS
#
app_name: "CarMaintenanceApp"
app_api_version: "/api/v1"

#
# SERVER SETTINGS
#
server_name: "CarMaintenance"
server_max_conns: "1000"
server_scheme: "http://"
server_host: "localhost"
server_port: ":9000"

base_url: "http://localhost:9000"
base_api_url: "http//localhost:9000/api/v1"

#
# SECURITY SETTINGS
#
hash_secret_key: "ThesisHash"
jwt_secret_key: "ThesisKey"
jwt_expired_in: 60
jwt_max_age: 60


#
# POSTGRES SETTINGS
#
postgres_server_name: "carMaintenance-db"
postgres_port: 5432
postgres_db_name: "car_maintenance_prod"
postgres_user_name: "postgres"
postgres_password: ""

#
# MAIL SETTINGS
#
mail_user_name: ""
mail_password: ""
mail_server_name: ""
mail_port: ""
mail_from_address: ""
mail_from_name: ""

