version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: carMaintenance-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "3YmCs1MzQ"
      POSTGRES_DB: "car_maintenance_dev"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carMaintenance-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carMaintenance-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "3YmCs1MzQ"
      DB_NAME: scrum_poker
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - scrumpoker-network

networks:
  scrumpoker-network:
    driver: bridge

volumes:
  postgres_data: