version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: carMaintenance-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "car_maintenance_prod"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - carMaintenance-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carMaintenance-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ""
      DB_NAME: CarMaintenanceProd
      ENV: PRODUCTION
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - carMaintenance-network

networks:
  carMaintenance-network:
    driver: bridge

volumes:
  postgres-data: